// examples/browser-vue-custom-element/src/App.vue
<template>
  <h2>YJS + Vue + CustomElement demo</h2>
  <button @click="newRoom">New room</button>
  <ul>
    <li v-for="id in roomIDs">
      <a :href="'#room:' + id">{{ id }}</a>
    </li>
  </ul>

  <my-editor v-if="roomId" ref="editor" :roomId="roomId"></my-editor>
</template>

<script>
import { defineCustomElement, h, onMounted, ref } from 'vue';
import MyEditor from './my-editor.ce.vue';

if (!customElements.get('my-editor')) {
  customElements.define('my-editor', defineCustomElement(MyEditor));
}

export default {
  name: 'App',
  data() {
    return {
      roomId: null,
      roomIDs: [],
      docs: [],
    };
  },
  created() {
    this.fetch();
    this.updateRoomFromHash();
    
    // Listen for hash changes
    window.addEventListener('hashchange', this.updateRoomFromHash);
  },
  beforeUnmount() {
    window.removeEventListener('hashchange', this.updateRoomFromHash);
  },
  methods: {
    updateRoomFromHash() {
      const docUrl = globalThis.location.hash.slice(1);
      if (docUrl.startsWith('room:')) {
        this.roomId = docUrl.substring('room:'.length);
      } else {
        this.roomId = null;
      }
    },
    async fetch() {
      const response = await fetch('/api/rooms');
      this.roomIDs = await response.json();
    },
    newRoom() {
      const roomId = String(Math.random());
      globalThis.location.hash = 'room:' + roomId;
      this.roomId = roomId;
      this.fetch();
    }
  },
};
</script>
<style>
@import '@kerebron/editor/assets/vars.css';
</style>

// examples/browser-react/src/App.tsx
import React, { useEffect, useState } from 'react';
import EditorYjs from './EditorYjs';
import '@kerebron/editor/assets/vars.css';

const App: React.FC = () => {
  const [roomIDs, setRoomIDs] = useState<string[]>([]);
  const [currentRoomId, setCurrentRoomId] = useState<string | null>(null);

  // Fetch list of existing rooms from backend
  const fetchRooms = async () => {
    try {
      const response = await fetch('/api/rooms');
      if (response.ok) {
        const ids: string[] = await response.json();
        setRoomIDs(ids);
      }
    } catch (err) {
      console.error('Failed to fetch rooms:', err);
    }
  };

  // Read current room from URL hash on mount and on hash change
  useEffect(() => {
    const readHash = () => {
      const hash = window.location.hash.slice(1);
      if (hash.startsWith('room:')) {
        setCurrentRoomId(hash.substring('room:'.length));
      } else {
        setCurrentRoomId(null);
      }
    };

    readHash(); // initial
    window.addEventListener('hashchange', readHash);
    fetchRooms();

    return () => {
      window.removeEventListener('hashchange', readHash);
    };
  }, []);

  // Refresh room list when entering a new room
  useEffect(() => {
    if (currentRoomId) {
      fetchRooms();
    }
  }, [currentRoomId]);

  const newRoom = () => {
    const newId = Math.random().toString(36).substring(2, 12);
    window.location.hash = 'room:' + newId;
    // hashchange will update currentRoomId
  };

  return (
    <div>
      <h2>Yjs + React Demo</h2>
      <button onClick={newRoom}>New Room</button>

      <>
        {roomIDs.length === 0 ? <p>No rooms yet. Create one above!</p> : (
          <ul>
            {roomIDs.map((id) => (
              <li key={id}>
                <a href={`#room:${id}`}>{id}</a>
              </li>
            ))}
          </ul>
        )}
      </>

      <section>
        {currentRoomId
          ? (
            <>
              <EditorYjs />
            </>
          )
          : (
            <p>
              Select a room or create a new one to start editing collaboratively
            </p>
          )}
      </section>
    </div>
  );
};

export default App;
