// examples/browser-vue/src/EditorYjs.vue
<template>
  <div>
    <div>
      <div ref="editor" class="kb-component"></div>
    </div>
    <div>
      <h5>Markdown</h5>
      <pre>{{ md }}</pre>
    </div>
    <div>
      <h5>ydoc</h5>
      <pre>{{ JSON.stringify(ydoc, null, 2) }}</pre>
    </div>
  </div>
</template>
<script lang="ts">
import { CoreEditor } from '@kerebron/editor';
import { YjsEditorKit } from '@kerebron/editor-kits/YjsEditorKit';
import { AdvancedEditorKit } from '@kerebron/editor-kits//AdvancedEditorKit';
import { createAssetLoad } from '@kerebron/wasm/web';

export default {
  name: 'my-editor',
  props: ['modelValue', 'roomId'],
  expose: ['loadDoc', 'loadDoc2'],
  data() {
    return {
      lastValue: null,
      ydoc: {},
      md: '',
      editor: null,
    };
  },
  async mounted() {
    this.$nextTick(() => {
      const docUrl = globalThis.location.hash.slice(1);
      let roomId;
      if (docUrl.startsWith('room:')) {
        roomId = docUrl.substring('room:'.length);
      } else {
        roomId = String(Math.random());
        globalThis.location.hash = 'room:' + roomId;
      }

      let userName = '';
      if (!userName) {
        userName = 'TODO ' + Math.floor(Math.random() * 100);
      }

      this.editor = CoreEditor.create({
        element: this.$refs.editor,
        assetLoad: createAssetLoad('/wasm'),
        editorKits: [
          new AdvancedEditorKit(),
          YjsEditorKit.createFrom(userName)
        ],
        // content: pmDoc
      });

      this.editor.addEventListener('transaction', async (ev: CustomEvent) => {
        this.lastValue = ev.detail.transaction.doc;
        const buffer = await this.editor.saveDocument('text/x-markdown');
        this.md = new TextDecoder().decode(buffer);
        // this.$emit('input', this.lastValue);
      });
    });
  },
  watch: {
    value(newValue) {
      if (newValue !== this.lastValue) {
        // this.state = createState(newValue, this.handle);
        // this.view.updateState(this.state);
      }
    },
    async roomId() {
      await this.editor.loadDocumentText('yjs', this.roomId);
    }
  },
  methods: {
    async loadDoc() {
      const buffer = new TextEncoder().encode(
        '# TEST \n\n1.  aaa **bold**\n2.  bbb\n\n```js\nconsole.log("TEST")\n```\n',
      );
      await this.editor.loadDocument('text/x-markdown', buffer);
    },
    loadDoc2() {
      const input = document.createElement('input');
      input.type = 'file';
      input.onchange = async (e) => {
        const file = e.target.files[0];
        console.log('Selected file:', file);
        await this.editor.loadDocument(
            file.type,
            new Uint8Array(await file.arrayBuffer()),
        );
      };
      input.click();
    },
  },
};
</script>
<style>
@import '@kerebron/editor/assets/index.css';
@import '@kerebron/extension-tables/assets/tables.css';
@import '@kerebron/extension-menu/assets/custom-menu.css';
@import '@kerebron/extension-codemirror/assets/codemirror.css';
</style>

// examples/browser-react/src/EditorYjs.tsx
// App.tsx or MyEditor.tsx
import React, { useEffect, useRef, useState } from 'react';
import * as Y from 'yjs';
import { WebsocketProvider } from 'y-websocket';
import * as random from 'lib0/random';
import { userColors } from '@kerebron/extension-yjs/userColors';
import { ExtensionYjs } from '@kerebron/extension-yjs';

import { CoreEditor } from '@kerebron/editor';
import { AdvancedEditorKit } from '@kerebron/editor-kits/AdvancedEditorKit';

const MyEditor: React.FC = () => {
  const editorRef = useRef<HTMLDivElement>(null);
  const editorInstance = useRef<CoreEditor | null>(null);
  const wsProvider = useRef<WebsocketProvider | null>(null);

  const [md, setMd] = useState<string>('');

  // Public methods (equivalent to expose in Vue)
  const loadDoc = async () => {
    if (!editorInstance.current) return;

    const content = `# TEST

1. aaa **bold**
2. bbb

\`\`\`js
console.log("TEST")
\`\`\`
`;

    const buffer = new TextEncoder().encode(content);
    await editorInstance.current.loadDocument('text/x-markdown', buffer);
  };

  const loadDoc2 = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.md,.odt,.docx';

    input.onchange = async (e: any) => {
      const file: File = e.target.files[0];
      if (!file || !editorInstance.current) return;

      const arrayBuffer = await file.arrayBuffer();
      const uint8Array = new Uint8Array(arrayBuffer);

      await editorInstance.current.loadDocument(
        file.type || 'application/octet-stream',
        uint8Array,
      );
    };

    input.click();
  };

  useEffect(() => {
    if (!editorRef.current) return;

    // Get room ID from URL hash
    const hash = window.location.hash.slice(1);
    if (!hash.startsWith('room:')) {
      return;
    }
    const roomId = hash.substring('room:'.length);

    // Initialize Yjs document and WebSocket provider
    const ydoc = new Y.Doc();
    const provider = new WebsocketProvider(
      'wss://localhost:8000/yjs',
      roomId,
      ydoc,
      {
        connect: true,
      },
    );

    wsProvider.current = provider;

    const userColor = userColors[random.uint32() % userColors.length];
    provider.awareness.setLocalStateField('user', {
      name: 'Anonymous ' + Math.floor(Math.random() * 100),
      color: userColor.color,
      colorLight: userColor.light,
    });

    // Initialize the editor
    const editor = new CoreEditor({
      element: editorRef.current,
      cdnUrl: 'https://localhost:8000/wasm/',
      extensions: [
        new AdvancedEditorKit(),
        new ExtensionYjs({ ydoc, provider }),
      ],
    });

    editorInstance.current = editor;

    // Listen to transactions and update markdown preview
    const onTransaction = async () => {
      if (!editorInstance.current) return;

      try {
        const buffer = await editorInstance.current.saveDocument(
          'text/x-markdown',
        );
        const markdown = new TextDecoder().decode(buffer);
        setMd(markdown);
      } catch (err) {
        console.error('Failed to save markdown:', err);
      }
    };

    editor.addEventListener('transaction', onTransaction);

    // Optional: Load initial document
    // loadDoc();

    // Cleanup on unmount
    return () => {
      editor.removeEventListener('transaction', onTransaction);
      editor.destroy();
      provider.destroy();
    };
  }, []);

  return (
    <div>
      <div>
        <div ref={editorRef} className='kb-component' />
      </div>

      <div>
        <div>
          <h5>Markdown Output</h5>
          <pre>{md || "Loading..."}</pre>
        </div>
      </div>
    </div>
  );
};

export default MyEditor;
